---
# tasks file for gitlab_runner_configure

- name: Copy undraw.svg 
  template:
    src: "{{ role_path }}/files/script.deb.sh"
    dest: "/tmp/script.deb.sh"
    mode: '0644'
  become: true

- name: Copy undraw.svg
  template:
    src: "{{ role_path }}/files/register.sh"
    dest: "/tmp/register.sh"
    mode: '0644'
  become: true

- name: Make script exec
  shell: chmod +x /tmp/script.deb.sh
  become: true

- name: Make script exec
  shell: chmod +x /tmp/register.sh
  become: true

- name: Add gitlab-runner repo
  shell: /tmp/script.deb.sh
  become: true

- name: Install req packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - gitlab-runner
      - ca-certificates
      - git        
      - gnupg         
      - lsb-release
    state: present
  become: true

- name: add-priveleg-true
  shell: sudo sed -i "30s~.*~    privileged = true~" /etc/gitlab-runner/config.toml

- name: Add gitlab-runner to group 'docker'
  user:
    name: gitlab-runner
    groups: docker
    append: yes
  become: true

- name: Change ownership of /etc/systemd/system
  ansible.builtin.file:
    path: /etc/systemd/system
    state: directory
    recurse: yes
    owner: gitlab-runner
    group: gitlab-runner
  become: true

- name: Register runner
  shell: /tmp/register.sh
