---
# tasks file for gitlab_runner_configure

- name: Install req packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - python3-pip 
      - python3.8-venv
      - gitlab-runner
      - ca-certificates
      - git        
      - gnupg         
      - lsb-release
    state: present
  become: true

#- name: Ansible user install 
#  shell: python3 -m pip install --user ansible
#  become: true

#- name: Install ansible
#  ansible.builtin.apt:
#    name:
#      - ansible
#    state: present
#  become: true

- name: add-priveleg-true
  shell: sudo sed -i "30s~.*~    privileged = true~" /etc/gitlab-runner/config.toml

- name: Add gitlab-runner to group 'docker'
  user:
    name: gitlab-runner
    groups: docker
    append: yes
  become: true

- name: Change ownership of /etc/systemd/system
  ansible.builtin.file:
    path: /etc/systemd/system
    state: directory
    recurse: yes
    owner: gitlab-runner
    group: gitlab-runner
  become: true

- name: Register runner
  shell: echo Hello! > /home/rh/hi.txt
